-- AlterTable
ALTER TABLE `note_tree` ADD COLUMN `depth` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `isLeaf` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `isUse` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `remark` VARCHAR(191) NULL,
    ADD COLUMN `status` VARCHAR(191) NULL;
